imports:
    - { resource: "@ThreeBRSSyliusPplParcelshopsPlugin/Resources/config/resources.yaml" }
    - { resource: "@ThreeBRSSyliusPplParcelshopsPlugin/Resources/config/twig_hooks/twig_hooks.yaml" }
